version: '3'
services:
    nginx:
        build: nginx
        container_name: nginx
        ports:
            - '8080:8080'
            - '8443:8443'
        volumes:
            - '..:/redcap' 
        links:
            - redcap
    db:
        build: postgres
        container_name: postgres
        environment:
            REDCAP_PASS: ${REDCAP_PASS}
            REDCAP_USER: ${REDCAP_USER}
            VAULT_PASS: ${VAULT_PASS}
            VAULT_USER: ${VAULT_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
            - '5432:5432'
        volumes: 
            - pgsql_data:/var/lib/postgresql/data 
    rabbit:
        image: rabbitmq:alpine
        container_name: rabbit
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - '5672:5672'
    vault:
        build: vault
        container_name: vault
        environment:
            VAULT_ADDR: http://127.0.0.1:8200
            VAULT_PASS: ${VAULT_PASS}
            VAULT_USER: ${VAULT_USER} 
        cap_add: 
            - IPC_LOCK
        volumes:
            - vault_keys:/vault/keys
        ports:
            - '8200:8200'
        links: 
            - db 
    redcap:
        build: redcap
        container_name: redcap
        volumes: 
            - '..:/redcap'
        ports: 
            - '8000:8000'
        links: 
            - db
            - rabbit
            - vault
volumes:
     pgsql_data:
         driver: local
     vault_keys:
         driver: local
     
